# Generated by Django 2.2 on 2021-07-19 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myoperations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='操作名称')),
                ('description', models.CharField(default='', max_length=50, verbose_name='操作原因')),
                ('operator', models.CharField(blank=True, default='', max_length=50, verbose_name='添加者')),
                ('deal_code', models.CharField(default='', max_length=16, verbose_name='业务号')),
                ('from_ips', models.CharField(default='', max_length=100, verbose_name='原始ip')),
                ('to_ips', models.CharField(default='', max_length=100, verbose_name='结果ip')),
                ('operation_time', models.DateTimeField(default=datetime.datetime(2021, 7, 19, 14, 58, 7, 931102), verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志管理',
                'verbose_name_plural': '操作日志管理',
            },
        ),
    ]
