# Generated by Django 2.2 on 2021-07-19 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0002_operation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='description',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='from_ips',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='to_ips',
        ),
        migrations.AddField(
            model_name='operation',
            name='add_ip',
            field=models.CharField(default='', max_length=100, verbose_name='新增ip'),
        ),
        migrations.AddField(
            model_name='operation',
            name='del_ip',
            field=models.CharField(default='', max_length=100, verbose_name='回收ip'),
        ),
        migrations.AddField(
            model_name='operation',
            name='descrption',
            field=models.CharField(default='', max_length=50, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='操作类型'),
        ),
        migrations.AddField(
            model_name='operation',
            name='vpn_deal_code',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='deal_code',
            field=models.CharField(default='', max_length=32, verbose_name='业务号码'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 15, 6, 32, 410657), verbose_name='操作时间'),
        ),
    ]
