# Generated by Django 2.2 on 2021-07-19 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0004_auto_20210719_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=32, verbose_name='性别')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(default='', max_length=50, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 15, 27, 53, 835121), verbose_name='操作时间'),
        ),
    ]
