# Generated by Django 2.2 on 2021-07-19 07:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0006_auto_20210719_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 15, 34, 54, 292575), verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myoperations.opetaion_type'),
        ),
    ]
