# Generated by Django 2.2 on 2021-07-19 07:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myoperations', '0007_auto_20210719_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='reason_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 15, 37, 6, 656930), verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myoperations.reason_type'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='vpn_deal_code',
            field=models.CharField(max_length=32, null=True, verbose_name='vpn业务号码'),
        ),
    ]
